apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpcrudapp-d
  namespace: phpcrudapp
  labels:
    app: phpcrudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpcrudapp
  template:
    metadata:
      labels:
        app: phpcrudapp
    spec:
      containers:
      - name: phpcrudapp
        image: aymenzarour/phpcrudapp:20
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-dev-params
                key: mysql-host
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-dev-params
                key: mysql-user
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-dev-params
                key: mysql-db
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-dev-secret
                key: mysql-pass
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpcrudapp-svc
  namespace: phpcrudapp
spec:
  type: NodePort
  selector:
    app: phpcrudapp
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30001
